"""Community types, roles and join requests

Revision ID: 864117ace452
Revises: 44b375f6f3a4
Create Date: 2024-11-09 22:02:06.102052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '864117ace452'
down_revision = '44b375f6f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('PUBLIC', 'PRIVATE', name='communitytype'), nullable=False))

    with op.batch_alter_table('user_community', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('MEMBER', 'ADMIN', 'CREATOR', name='userrole'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_community', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('MEMBER', 'ADMIN', 'CREATOR', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('join_request')
    # ### end Alembic commands ###
