"""Añadido un nuevo atributo a DSMetrics

Revision ID: b60091568f6e
Revises: 44b375f6f3a4
Create Date: 2024-12-03 11:44:45.360280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60091568f6e'
down_revision = '44b375f6f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_products', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.drop_column('number_of_products')

    # ### end Alembic commands ###
