name: Deploy with Vagrant

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - feature/109-vagrant

jobs:
  deploy:
    name: Deploy VM with Vagrant and Provision with Ansible
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Crear archivo .env
        run: |
          echo "FLASK_ENV=testing" > .env
          echo "MARIADB_HOSTNAME=127.0.0.1" >> .env
          echo "MARIADB_PORT=3306" >> .env
          echo "MARIADB_TEST_DATABASE=uvlhubdb_test" >> .env
          echo "MARIADB_USER=uvlhub_user" >> .env
          echo "MARIADB_PASSWORD=uvlhub_password" >> .env

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Set up Vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox

      - name: Initialize Vagrant
        run: |
          cd vagrant
          vagrant up

      - name: Provision Vagrant VM with Ansible
        run: |
          vagrant provision
          vagrant ssh

      - name: Clean up after deployment
        run: |
          vagrant destroy -f
